services:
  # 🛠️ Container Principal de Desenvolvimento
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
      - vscode-extensions:/home/vscode/.vscode-server/extensions
      - composer-cache:/home/vscode/.cache/composer
      - npm-cache:/home/vscode/.cache/npm
      - ~/.ssh:/home/vscode/.ssh-localhost:ro
    command: sleep infinity
    networks:
      - reidooleo-dev
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DISPLAY=:0
      - COMPOSER_CACHE_DIR=/home/vscode/.cache/composer
      - NPM_CONFIG_CACHE=/home/vscode/.cache/npm
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=rei_do_oleo_dev
      - DB_USERNAME=rei_do_oleo
      - DB_PASSWORD=secret123
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8100:8000"   # Laravel API
      - "3100:3000"   # React Frontend
      - "5200:5173"   # Vite Dev Server

  # 🗄️ MySQL Database 8.0
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb-buffer-pool-size=128M
      --max-connections=200
      --bind-address=0.0.0.0
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: rei_do_oleo_dev
      MYSQL_USER: rei_do_oleo
      MYSQL_PASSWORD: secret123
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_RANDOM_ROOT_PASSWORD: "no"
    ports:
      - "3310:3306"
    networks:
      - reidooleo-dev
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot123", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # 📦 Redis Cache & Sessions 7.x
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - redis-data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6400:6379"
    networks:
      - reidooleo-dev
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # 💾 phpMyAdmin - Interface Web MySQL
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root123
      MYSQL_ROOT_PASSWORD: root123
      PMA_ARBITRARY: 1
      PMA_ABSOLUTE_URI: http://localhost:8110/
    ports:
      - "8110:80"
    networks:
      - reidooleo-dev
    depends_on:
      mysql:
        condition: service_healthy

  # 🔍 Redis Commander - Interface Web Redis
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379
      HTTP_USER: admin
      HTTP_PASSWORD: secret123
    ports:
      - "6410:8081"
    networks:
      - reidooleo-dev
    depends_on:
      redis:
        condition: service_healthy

  # 📧 MailHog - Captura de Emails (Desenvolvimento)
  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - "1030:1025"  # SMTP
      - "8030:8025"  # Web UI
    networks:
      - reidooleo-dev

volumes:
  vscode-extensions:
  mysql-data:
  redis-data:
  composer-cache:
  npm-cache:

networks:
  reidooleo-dev:
    external: true
    name: devcontainer_reidooleo-dev 